default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: vagrant
  password: vagrant
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: unioeste_app_tcc_development

test:
  <<: *default
  database: unioeste_app_tcc_test

production:
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8
  pool: 5
  database: unioeste_app_tcc
  username: vagrant
  password: vagrant
