# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7ebbd5c9e21a0a06ffe03bad3c83e054b1d88c6c0ee36ba44dad82618a8763954e2c0ebe2177258d81132af5739e798e5def48ceb1234d8e470763215341e5

test:
  secret_key_base: d017b70db21a667c3669eadfe1670119cf47ffc8e301336634be3a8203c60ba91a9e3a0916f7b36b3c4d66e66fd811da029dbfc65c578effad9ef5d624ae0ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
